### ISSUE TITLE
Dataset encryption passphrase length limit on unlock prompt issue

### ISSUE THREAD

**Issue by hyperkit** [IkerSaint/ZFS-Master-Unraid#4]
When creating a dataset with a relative long encryption passphrase (says **128** characters) it works fine. But after that dataset is locked and try to unlock that again with the ZFS master "Unlock dataset" action on the dataset, the prompt to enter the passphrase only allows **64** characters (Which the users might be unawared because it is masked).

<img width="317" alt="image" src="https://github.com/IkerSaint/ZFS-Master-Unraid/assets/5856896/911544b5-94e8-4e73-ad5b-dd76d68bf00a">
<img width="431" alt="image" src="https://github.com/IkerSaint/ZFS-Master-Unraid/assets/5856896/c8ff6b5b-54b7-4c3b-918d-b83af3ab4360">

This results the dataset will not be able to be unlocked anymore (complaining incorrect passphrase), unless entering F12 mode to change the prompt's password input maxlength to say like **128** characters again.

**Comment by IkerSaint** [comment]
Nice catch!, it will be fixed on the next version.

**Comment by IkerSaint** [comment]
Addressed on the latest version.
