### ISSUE TITLE
Unlock Dataset passphrase entry is not in password field.

### ISSUE THREAD

**Issue by dotorg** [IkerSaint/ZFS-Master-Unraid#5]
Pretty much what the subject says. When unlocking a dataset, the window to enter the passphrase is a plan-text field, not a password field. The prompt to create an encrypted dataset is properly using a password field.

**Comment by IkerSaint** [comment]
This is a known issue introduced for compatibility with ne unraid versions. I have tried to fixed several times, but with the latest Unraid version, the "theming" applied make some controls look very awful, including the password fields. I'll try to mask the password for the next version but it's not really a priority right now.

**Comment by IkerSaint** [comment]
Addressed on the latest version.
