### ISSUE TITLE
Long "Main" Loading Times

### ISSUE THREAD

**Issue by Renegade605** [IkerSaint/ZFS-Master-Unraid#6]
When there are many zpools on a system, the Main page of the Unraid WebUI can take a long time to load, especially if the system if busy with disk tasks like a scrub or parity check.

For reference, my system has 9 pools and load times are at best ~8 seconds but during heavy system load I've observed load times in excess of 2 minutes for the main page.

Suggested solution: Allow the page to load without ZFS Master content, then dynamically fill in the content afterwards. Unassigned devices appears to do this already.

Alternatively, do not load ZFS Master content at all until the user clicks the refresh button once, or show ZFS Master on a completely separate page. (Both less desirable, but potentially easier to implement in the short term.)

**Comment by LoveBootCaptain** [comment]
it also causes to spin up all drives which are in standby mode. this may lead to the long loading times that @Renegade605 mentioned.

would also prefer to see those information on a seperate page wich also include to "lazy load" the informations in case the disks are spun down.

maybe also add an option die skip spinning up disks (like: reload from disk is optional for snapshot informations)

hope there is a fix to both issues.

thx and kind regards from berlin
great plugin :)

**Comment by IkerSaint** [comment]
Please check the comments on the support thread; both issues have been addressed and are in the works now.

https://forums.unraid.net/topic/122261-plugin-zfs-master/

**Comment by Renegade605** [comment]
@LoveBootCaptain I specifically did not mention spinning up drives because it isn't a concern to me. Unlike most misguided Unraid users, I leave all my drives spinning 24/7.

@IkerSaint, thanks. Without trying to sound like I'm being difficult, this is why forum 'suppprt' is the worst kind of support. "You must read 9 pages of mostly unrelated comments to get an answer to your question" is frustrating for everyone involved. You, because you've already answered this. Me, because I still don't know what the answer is.
